[component]
structures = [ "content_blocks" ]
label = "Contact Form"
description = "Generic contact form"
icon = "wysiwyg"
tags = ["Text"]

[props]
form_title = "Escríbme"
form_description = "¿Necesitas más información? Escríbeme ahora mismo."
form_success_page = "/"
form_submission_email = "csantosm.dev@gmail.com" # Add your email for contact form
form_button_text = "Enviar"